version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.12
    ports:
      - "5672"
      - "15672:15672"
  payment:
    build:
      context: .
    image: robotshop/rs-payment
    depends_on:
      - rabbitmq
    ports:
      - "8080:8080"
