apiVersion: v1
kind: Service
metadata:
  name: dispatch
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
  labels:
    app.kubernetes.io/name: robot-shop
    service: dispatch
spec:
  ports:
  - name: http
    port: 8080
  selector:
    service: dispatch
