apiVersion: v1
kind: Service
metadata:
  name: dispatch
  labels:
    app.kubernetes.io/name: robot-shop
    service: dispatch
spec:
  ports:
  - name: http
    port: 8080
  selector:
    service: dispatch
