apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app.kubernetes.io/name: robot-shop
    service: mongodb
    type: infra
spec:
  ports:
  - name: mongo
    port: 27017
  - name: http-metrics
    port: 9216
  selector:
    service: mongodb
