apiVersion: v1
kind: Service
metadata:
  name: ratings
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    prometheus.io/path: "/metrics"
  labels:
    app.kubernetes.io/name: robot-shop
    service: ratings
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    service: ratings
