apiVersion: v1
kind: Service
metadata:
  name: ratings
  labels:
    app.kubernetes.io/name: robot-shop
    service: ratings
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    service: ratings
